/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chinachess_mid_NativeInterface */

#ifndef _Included_chinachess_mid_NativeInterface
#define _Included_chinachess_mid_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef chinachess_mid_NativeInterface_WINNER_BLACK
#define chinachess_mid_NativeInterface_WINNER_BLACK -1L
#undef chinachess_mid_NativeInterface_WINNER_RED
#define chinachess_mid_NativeInterface_WINNER_RED 1L
#undef chinachess_mid_NativeInterface_WINNER_NONE
#define chinachess_mid_NativeInterface_WINNER_NONE 0L

#undef chinachess_mid_NativeInterface_JNI_TRUE
#define chinachess_mid_NativeInterface_JNI_TRUE 1L
#undef chinachess_mid_NativeInterface_JNI_FALSE
#define chinachess_mid_NativeInterface_JNI_FALSE 0L
/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    initBoard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_initBoard
  (JNIEnv *, jobject);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    moveChess
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_moveChess
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    getNextMove
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_getNextMove
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    setChessIdByPosition
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_setChessIdByPosition
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    resetBoardDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_resetBoardDefault
  (JNIEnv *, jobject);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    resetBoard
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_resetBoard
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    clearBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_chinachess_mid_NativeInterface_clearBoard
  (JNIEnv *, jobject);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    setGameLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_chinachess_mid_NativeInterface_setGameLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    getGameStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chinachess_mid_NativeInterface_getGameStatus
  (JNIEnv *, jobject);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    setGameStatus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_chinachess_mid_NativeInterface_setGameStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     chinachess_mid_NativeInterface
 * Method:    getAuthorName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_chinachess_mid_NativeInterface_getAuthorName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
